// ─── SAMPLE DATA ──────────────────────────────────────────────────────────────
// Replace or extend this with your own data.
// All fields marked optional can be omitted.

export const AGENCIES = [
  { id: "hololive",   name: "Hololive Production", image: "https://i.imgur.com/QZFgEcE.png", members: 70, subscribers: 180_000_000 },
  { id: "nijisanji",  name: "NIJISANJI",            image: "https://i.imgur.com/5VJZhj5.png", members: 200, subscribers: 250_000_000 },
  { id: "vspo",       name: "VSPO!",                image: "",                                members: 12,  subscribers: 15_000_000 },
  { id: "774inc",     name: "774 Inc.",              image: "",                                members: 20,  subscribers: 20_000_000 },
  { id: "prism",      name: "PRISM Project",         image: "",                                members: 15,  subscribers: 8_000_000 },
  { id: "independent",name: "Independent",           image: "",                                members: 0,   subscribers: 0 },
];

export const VTUBERS = [
  {
    id: "gawr-gura",
    name: "Gawr Gura",
    image: "https://static.wikia.nocookie.net/virtualyoutuber/images/0/09/Gawr_Gura_Portrait.png/revision/latest/scale-to-width-down/350",
    agency: "hololive",
    status: "active",
    debut: "2020-09-13",
    retired: null,
    subscribers: 4_420_000,
    channel: "https://www.youtube.com/@GawrGura",
    channelType: "youtube",
    gender: "female",
    model: "2D",
    language: "English",
    designer: "Amashiro Natsuki",
    modeler2d: "Warabeda Meijin",
    modeler3d: null,
    birthday: "June 20",
    height: 141,
    weight: null,
    bloodType: "A",
    zodiac: "Gemini",
    description: "A shark girl from Atlantis who is actually a descendant of ancient, underwater civilization.",
    tags: ["shark", "cute", "EN"],
  },
  {
    id: "kizuna-ai",
    name: "Kizuna AI",
    image: "https://static.wikia.nocookie.net/virtualyoutuber/images/9/95/Kizuna_AI_Portrait.png/revision/latest/scale-to-width-down/350",
    agency: "independent",
    status: "retired",
    debut: "2016-11-29",
    retired: "2022-02-26",
    subscribers: 3_000_000,
    channel: "https://www.youtube.com/@KizunaAI",
    channelType: "youtube",
    gender: "female",
    model: "3D",
    language: "Japanese",
    designer: "Tadahito Mochinaga",
    modeler2d: null,
    modeler3d: "Tadahito Mochinaga",
    birthday: "June 30",
    height: 158,
    weight: 49,
    bloodType: "O",
    zodiac: "Cancer",
    description: "The pioneer of the VTuber movement. Known as 'AI-chan', she was the first major virtual YouTuber.",
    tags: ["pioneer", "AI", "JP"],
  },
  {
    id: "hoshimachi-suisei",
    name: "Hoshimachi Suisei",
    image: "https://static.wikia.nocookie.net/virtualyoutuber/images/5/5b/Hoshimachi_Suisei_Portrait.png/revision/latest/scale-to-width-down/350",
    agency: "hololive",
    status: "active",
    debut: "2018-03-18",
    retired: null,
    subscribers: 1_980_000,
    channel: "https://www.youtube.com/@SuiseiChannel",
    channelType: "youtube",
    gender: "female",
    model: "2D",
    language: "Japanese",
    designer: "Sui-chan",
    modeler2d: "Okazaki Yumemi",
    modeler3d: "Tokinohane Shin",
    birthday: "March 22",
    height: 160,
    weight: null,
    bloodType: "A",
    zodiac: "Aries",
    description: "An idol who came from a distant star, aiming to stand on the grandest stage in the galaxy.",
    tags: ["idol", "singing", "JP"],
  },
  {
    id: "mori-calliope",
    name: "Mori Calliope",
    image: "https://static.wikia.nocookie.net/virtualyoutuber/images/b/b2/Mori_Calliope_Portrait.png/revision/latest/scale-to-width-down/350",
    agency: "hololive",
    status: "active",
    debut: "2020-09-12",
    retired: null,
    subscribers: 2_370_000,
    channel: "https://www.youtube.com/@MoriCalliope",
    channelType: "youtube",
    gender: "female",
    model: "2D",
    language: "English",
    designer: "Yukisame",
    modeler2d: "jujube",
    modeler3d: null,
    birthday: "April 4",
    height: null,
    weight: null,
    bloodType: null,
    zodiac: "Aries",
    description: "Death's first apprentice, a Grim Reaper who creates rap music about mortality.",
    tags: ["rap", "music", "EN"],
  },
  {
    id: "nijisanji-kuzuha",
    name: "Kuzuha",
    image: "https://static.wikia.nocookie.net/virtualyoutuber/images/7/72/Kuzuha_Portrait.png/revision/latest/scale-to-width-down/350",
    agency: "nijisanji",
    status: "active",
    debut: "2018-08-17",
    retired: null,
    subscribers: 1_340_000,
    channel: "https://www.youtube.com/@Kuzuha_Channel",
    channelType: "youtube",
    gender: "male",
    model: "2D",
    language: "Japanese",
    designer: "Sasama Yohsuke",
    modeler2d: "Iida Pochi",
    modeler3d: null,
    birthday: "December 17",
    height: 175,
    weight: null,
    bloodType: "AB",
    zodiac: "Sagittarius",
    description: "A vampire king who streams games. One of the most subscribed male VTubers.",
    tags: ["vampire", "gaming", "JP"],
  },
  {
    id: "inugami-korone",
    name: "Inugami Korone",
    image: "https://static.wikia.nocookie.net/virtualyoutuber/images/f/fd/Inugami_Korone_Portrait.png/revision/latest/scale-to-width-down/350",
    agency: "hololive",
    status: "active",
    debut: "2019-04-13",
    retired: null,
    subscribers: 2_140_000,
    channel: "https://www.youtube.com/@InugamiKorone",
    channelType: "youtube",
    gender: "female",
    model: "2D",
    language: "Japanese",
    designer: "Fukahire Sanba",
    modeler2d: "Shin Umiushi",
    modeler3d: null,
    birthday: "October 26",
    height: 152,
    weight: null,
    bloodType: "A",
    zodiac: "Scorpio",
    description: "A dog girl who loves retro games and is known for her marathon gaming sessions.",
    tags: ["dog", "retrogames", "JP"],
  },
  {
    id: "oozora-subaru",
    name: "Oozora Subaru",
    image: "https://static.wikia.nocookie.net/virtualyoutuber/images/a/a6/Oozora_Subaru_Portrait.png/revision/latest/scale-to-width-down/350",
    agency: "hololive",
    status: "active",
    debut: "2019-09-02",
    retired: null,
    subscribers: 1_500_000,
    channel: "https://www.youtube.com/@OozoraSubaru",
    channelType: "youtube",
    gender: "female",
    model: "2D",
    language: "Japanese",
    designer: "Yagami Sora",
    modeler2d: "Pochi Iida",
    modeler3d: null,
    birthday: "September 17",
    height: 153,
    weight: null,
    bloodType: "O",
    zodiac: "Virgo",
    description: "An energetic duck-themed streamer known for her loud personality and love of sports.",
    tags: ["duck", "sports", "JP"],
  },
  {
    id: "nijisanji-lize",
    name: "Lize Helesta",
    image: "https://static.wikia.nocookie.net/virtualyoutuber/images/0/0f/Lize_Helesta_Portrait.png/revision/latest/scale-to-width-down/350",
    agency: "nijisanji",
    status: "active",
    debut: "2019-02-08",
    retired: null,
    subscribers: 840_000,
    channel: "https://www.youtube.com/@LizeHelesta",
    channelType: "youtube",
    gender: "female",
    model: "2D",
    language: "Japanese",
    designer: "Kanda Done",
    modeler2d: "Kanda Done",
    modeler3d: null,
    birthday: "August 19",
    height: 168,
    weight: null,
    bloodType: "B",
    zodiac: "Leo",
    description: "A royalty from another world, known for her elegance and love of games.",
    tags: ["royal", "JP"],
  },
];

export const EVENTS = [
  { id: 1, type: "birthday",    vtuberId: "gawr-gura",        date: "June 20",     year: null },
  { id: 2, type: "anniversary", vtuberId: "gawr-gura",        date: "Sep 13", year: 2020 },
  { id: 3, type: "birthday",    vtuberId: "hoshimachi-suisei", date: "March 22",    year: null },
  { id: 4, type: "anniversary", vtuberId: "hoshimachi-suisei", date: "March 18",    year: 2018 },
  { id: 5, type: "birthday",    vtuberId: "mori-calliope",     date: "April 4",     year: null },
  { id: 6, type: "birthday",    vtuberId: "inugami-korone",    date: "October 26",  year: null },
  { id: 7, type: "birthday",    vtuberId: "oozora-subaru",     date: "Sep 17",      year: null },
  { id: 8, type: "anniversary", vtuberId: "nijisanji-kuzuha",  date: "Aug 17",      year: 2018 },
];

export const VIDEOS = [
  { id: 1, vtuberId: "gawr-gura",         title: "Minecraft survival #42", duration: 7200,  views: 1_200_000, date: "2024-01-15", url: "#" },
  { id: 2, vtuberId: "hoshimachi-suisei", title: "Stellar Stellar [Live]",  duration: 3600,  views: 2_500_000, date: "2024-02-01", url: "#" },
  { id: 3, vtuberId: "mori-calliope",     title: "Rap god practice",        duration: 5400,  views: 800_000,   date: "2024-01-20", url: "#" },
  { id: 4, vtuberId: "inugami-korone",    title: "Donkey Kong 64 – Day 1",  duration: 21600, views: 950_000,   date: "2024-01-25", url: "#" },
  { id: 5, vtuberId: "nijisanji-kuzuha",  title: "VALORANT ranked grind",   duration: 14400, views: 1_100_000, date: "2024-01-30", url: "#" },
];
